### ISSUE TITLE
0.3 alpha burndown issue

### ISSUE THREAD

**Issue by aturon** [rust-lang-nursery/futures-rs#1033]
This issue is for tracking/mentoring the steps needed to get a complete 0.3 branch together.

These issues are listed in roughly order of increasing difficulty, and in the most natural order for completion.

- [ ] **Remove `futures-stable`**
  - This should no longer be relevant

- [ ] **Switch 0.3 branch to use task system from `std`**. Now that the core task definitions [have landed in `std`](https://github.com/rust-lang/rust/pull/51263), the 0.3 branch should be switched over to use these definitions from nightly. That means:
  - Removing the various task/executor definitions in the futures crate and replacing them with re-exports
  - Similarly for the `Future` trait itself

- [ ] **Update `futures-executor` in 0.3**. Right now, this crate is [not part of the 0.3 branch](https://github.com/rust-lang-nursery/futures-rs/blob/0.3/Cargo.toml#L7), and needs to be updated:
  - Its [Cargo.toml](https://github.com/rust-lang-nursery/futures-rs/blob/0.3/futures-executor/Cargo.toml) should be updated to use `0.3.0-alpha` throughout
  - All uses of `Future` should be updated to work with the new definitions (which means dealing with pinning, etc). E.g. the [Spawn future](https://github.com/rust-lang-nursery/futures-rs/blob/0.3/futures-executor/src/spawn.rs#L31).
  - The [`unsafe_*` macros](https://github.com/rust-lang-nursery/futures-rs/blob/0.3/futures-core/src/lib.rs#L43-L63) are really useful for working with pinned data. A good example of using these macros is the [`Map` combinator](https://github.com/rust-lang-nursery/futures-rs/blob/0.3/futures-util/src/future/map.rs#L26-L48).
  - The various `spawn` functions will have to be updated to make the 0.3 revisions (with `TaskObj` etc)

- [ ] **Reinstate [the prelude](https://github.com/rust-lang-nursery/futures-rs/blob/0.3/futures-util/src/lib.rs#L79-L85)**

- [ ] **Get the `futures` top-level crate compiling**

- [ ] **Get tests working**
  - Start with `futures-core`, then move to `futures-util`

- [ ] **Reinstate the [`Future::join` combinator](https://github.com/rust-lang-nursery/futures-rs/blob/0.3/futures-util/src/future/mod.rs#L23)**

- [ ] **Reinstate the [`Future::select` combinator](https://github.com/rust-lang-nursery/futures-rs/blob/0.3/futures-util/src/future/mod.rs#L25)**

- [ ] **Reinstate the [`join_all`, `select_all`, `select_ok` combinators](https://github.com/rust-lang-nursery/futures-rs/blob/0.3/futures-util/src/future/mod.rs#L54-L56)**
  - This will require some design work to re-think these combinators given our new error handling approach -- i.e. how to divide with the ones [here](https://github.com/rust-lang-nursery/futures-rs/blob/0.3/futures-util/src/try_future/mod.rs#L17)

- [ ] **Reinstate the [`Future::shared` combinator](https://github.com/rust-lang-nursery/futures-rs/blob/0.3/futures-util/src/future/mod.rs#L57)**

- [ ] **Reinstate the [missing `Stream` combinators](https://github.com/rust-lang-nursery/futures-rs/blob/0.3/futures-util/src/stream/mod.rs)**

- [ ] **Reinstate [`with_flat_map`](https://github.com/rust-lang-nursery/futures-rs/blob/0.3/futures-util/src/sink/mod.rs#L34)**

- [ ] **Figure out how to update the async/await macro code**

**Comment by aturon** [comment]
cc @majorbreakfast @cramertj

**Comment by aturon** [comment]
Let's use this issue to coordinate remaining work. If you're interested in taking on any of these items, speak up here!

**Comment by aturon** [comment]
Btw, @cramertj estimates to be within a couple weeks of async notation landing in nightly; it'd be awesome to intercept that with an alpha release!

**Comment by aturon** [comment]
@Nemo157 btw, do you have any interest in taking any of these on? @cramertj and I are otherwise-occupied.

**Comment by tinaun** [comment]
im going to try to do the first two things listed here - though ive noticed that the definitions in the crate has a lot more inherent methods and trait impls than the ones in std, how should i handle those without orphan rules getting in the way? a whole lot of extension traits?

**Comment by MajorBreakfast** [comment]
Quick update:
- **Switch 0.3 branch to use task system from `std`:** @tinaun has provided a PR https://github.com/rust-lang-nursery/futures-rs/pull/1034 (open)
- **Update futures-executor in 0.3:** I provided a PR https://github.com/rust-lang-nursery/futures-rs/pull/1037 (open)

**Comment by MajorBreakfast** [comment]
#1034 has been merged
@aturon can you update the checkbox?

**Comment by MajorBreakfast** [comment]
My PR https://github.com/rust-lang-nursery/futures-rs/pull/1037 was merged! 🎉
- the `futures` crate now works
  - the prelude is back again
  - all the stuff from the other crates is exported
  - the tests were disabled. They need to be ported
- `futures-core`: Some exports where added
- the `futures-executors` crate now works
  - The `LocalPool` can ATM only execute `Send`able futures because it uses `TaskObj` internally. Some kind of `LocalTaskObj` needs to be added to make it accept non-`Send` tasks. Maybe add `LocalTaskObj` that is `?Send` inside `futures-core` and add a `From<TaskObj>` impl that uses `transmute`?
  - Some tests were disabled because of this
  - Benchmarks still need to be ported
  - `stream::FuturesUnordered` (for efficient single threaded polling of futures with support for wake up form other threads, used by `LocalPool`) was refactored:
    - it was made pinning-aware
    - the file was split up into submodules
    - many identifiers were renamed
    - the algorithm works as before
- the `future-util` crate now works
  - The tests and doc tests run (except for `Fanout`. Its tests depend on not yet converted functionality)
  - Documentation remains outdated
  - Some stuff needs to be renamed in order to make sense now that futures don't have an associated error type anymore, e.g. `TryFutureExt::recover` should be renamed to `unwrap_or_else`
  - Some functionality still needs to be ported
  - Benchmarks still need to be ported

**Comment by aturon** [comment]
This is done! https://rust-lang-nursery.github.io/futures-rs/blog/2018/07/19/futures-0.3.0-alpha.1.html
