### ISSUE TITLE
Cargo cannot install crate?

### ISSUE THREAD

**Issue by akshaynanavati** [rust-lang-nursery/futures-rs#1052]
I have `futures = "0.2.1"` in my cargo.toml, yet I get the following when I try to build:

```
Updating registry `https://github.com/rust-lang/crates.io-index`
error: no matching version `^0.2` found for package `futures`
location searched: registry `https://github.com/rust-lang/crates.io-index`
versions found: 0.1.21, 0.1.20, 0.1.18, ...
```

Cargo version:

```
$ cargo --version
cargo 1.28.0-nightly (e2348c2db 2018-06-07)
```

Any help would be appreciated.

**Comment by MajorBreakfast** [comment]
Version 0.2 has been yanked from the fututres crate. It has been republished as the futures-preview crate.

https://github.com/rust-lang-nursery/futures-rs/issues/1039

I am sure that this will be communicated widely soon. This issue should best be kept open until that happened so that other people can easily find it.

**Comment by akshaynanavati** [comment]
Thanks. Is there a more recent version of futures in the nightly build, should I instead use futures 0.1.x, or should I use futures-preview? I'd like to use the one that is most recent and closest to being standardized (if this is possible).

**Comment by MajorBreakfast** [comment]
In that case I recommend using the 0.3 branch. It's not yet available on crates.io and currently in pre-alpha state, but most of it already works. Just don't trust any descriptions in the documentation, because in most cases only the code examples were updated to make them compile ;-)
