### ISSUE TITLE
`poll` is not given any information as to *which* sub-future needs to be polled

### ISSUE THREAD

**Issue by DemiMarie** [rust-lang-nursery/futures-rs#1061]
### The basic problem

`Future::poll` has no idea whatsoever which child future needed to be polled.  Therefore, it must poll all of them every time.  This leads to #1004.

This could be a big problem when one future is waiting for many events to complete, and arrive staggered, so that every future gets polled O(n) times, causing O(n^2) CPU consumption.

This is in contrast to the behavior of JS/Java/.NET programs, where the task explicitly calls its callback.  The callback thus knows *exactly* where to begin execution, avoiding unnecessary work.

### One Solution: Explicit Callbacks

In this approach, `Future::poll` gains an additional parameter, becoming

```rust
trait Future {
    type Item;
    type Error;

    fn poll(self: Pin<Self>, cx: &mut task::Context, cb: Pin<FnMut() -> ()>) -> Poll<Self::Item, Self::Error>;
}
```

That is, each future gets an explicit callback argument.  I could have gotten the exact type of the callback wrong — this is still a proof of concept,

This approach is that used by GCd languages, and has the same advantages.  It also leads to some knotty lifetime problems: the callback is not allowed to outlive its containing future, but there is nothing at the type level that can enforce this, since a pointer to it will be passed to a system API for event loop handling.  This is the classic circular reference problem.  Since everything is immovable (as guaranteed by `Pin`), we can safely hold on to a pointer to the callback (to invalidate it if the destructor of `self` runs), but I do not see how to tell the type system we can.

Furthermore, this runs into problems with object safety.  This is not an issue in GCd languages (where everything is boxed, hence has the same size), but is a big issue in Rust.  Specifically, `FnOnce` is not object-safe, but we can specify that the callback is to be called exactly once, when `Future::poll` will return `Ok(Async::Ready(_))`.  Calling `Future::poll` before the callback has been called will need to be detected, but could just `panic!()`.

**Comment by MajorBreakfast** [comment]
A mechanism very similar to this already exists. As @carllerche already mentioned, it is used in `FuturesUnordered`, also, a different implementation is used in `ThreadPool`. How it works is that the context given to the future contains a waker with a `Waker::wake` method on it. Whenever a future has returned `Poll::Pending`, it *must* call this method once it can make further progress and should be polled again. What the waker does can be fully customized. `FuturesUnordered` for instance has a "ready to run" queue internally in form of an atomic linked list and whenever the waker for one of its futures is called it enqueues the future. The only caveat is that the waker implementation needs to be thread safe because the waker is usually given to another thread.

https://github.com/rust-lang-nursery/futures-rs/blob/0.3/futures-util/src/stream/futures_unordered/mod.rs

**Comment by DemiMarie** [comment]
I did not think of this, thank you!

Could this trick also be used by FutureExt::and_then and other
combinators?  The use case I am thinking of is many calls to `.and_then`

On Jul 3, 2018 1:19 AM, "Josef Brandl" <notifications@github.com> wrote:

A mechanism very similar to this already exists. As @carllerche
<https://github.com/carllerche> already mentioned, it is used in
FuturesUnordered, also, a different implementation is used in ThreadPool.
How it works is that the context given to the future contains a waker with
a Waker::wake method on it. Whenever a future has returned Poll::Pending,
it *must* call this method once it can make further progress and should be
polled again. What the waker does can be fully customized. FuturesUnordered
for instance has a "ready to run" queue internally in form of an atomic
linked list and whenever the waker for one of its futures is called it
enqueues the future. The only caveat is that the waker implementation needs
to be thread safe because the waker is usually given to another thread.

https://github.com/rust-lang-nursery/futures-rs/blob/0.3/futures-util/src/stream/futures_unordered/mod.rs

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rust-lang-nursery/futures-rs/issues/1061#issuecomment-402016107>,
or mute the thread

**Comment by MajorBreakfast** [comment]
(I deleted my previous comment. I got your thread mixed up with another thread)

This approach only makes sense for combinators that take a large number of futures. Combinators like `and_then` only have one future to wake and they don't do any work themselves, so they can simply pass their context on to their child future:

https://github.com/rust-lang-nursery/futures-rs/blob/844a9202bf5f40a292dbc54cafe359666678f9f9/futures-util/src/future/map.rs#L40

This is actually where Rust's futures shines: Tiny futures like `map()` don't require a single heap allocation. They just stack together into one gigantic type.

`FuturesUnordered` does rely on heap allocations (it uses `Arc`) because it lets you push additional futures into it whenever you wish. Stream combinators like `buffered()` use it to run many things concurrently. Here it pushes more things into the queue until the limit is reached (`in_progress_queue` is a `FutureUnordered` instance):

https://github.com/rust-lang-nursery/futures-rs/blob/844a9202bf5f40a292dbc54cafe359666678f9f9/futures-util/src/stream/buffered.rs#L128-L133

**Comment by DemiMarie** [comment]
Sorry, I think I did not explain what the problem is.  The problem is that
`poll` takes time linear in the depth of the call stack.  So repeated calls
to `.and_then` are O(n^2).  Similarly, simple wait-for-any futures are
O(n^2) *even if they do not allow dynamically adding futures*.

What I was referring to was not the queue, but the idea of advancing the
state machine directly from the `waker`, rather than waiting for `poll` to
be called again.  The hard part is that there is no guarantee I can find
that the future will not be destroyed in the meantime, or that the `waker`
will be called on the same thread as the object is destroyed.

On Jul 4, 2018 2:59 AM, "Josef Brandl" <notifications@github.com> wrote:

(I deleted my previous comment. I got your thread mixed up with another
thread)

This approach only makes sense for combinators that take a large number of
futures. Combinators like and_then only have one future to wake and they
don't do any work themselves, so they can simply pass their context on to
their child future:

https://github.com/rust-lang-nursery/futures-rs/blob/844a9202bf5f40a292dbc54cafe359666678f9f9/futures-util/src/future/map.rs#L40

This is actually where Rust's futures shines: Tiny futures like map() don't
require a single heap allocation. They just stack together into one
gigantic type.

FuturesUnordered does rely on heap allocations (it uses Arc) because it
lets you push additional futures into it whenever you wish. Stream
combinators like buffered() use it to run many things concurrently. Here it
pushes more things into the queue until the limit is reached (
in_progress_queue is a FutureUnordered instance):

https://github.com/rust-lang-nursery/futures-rs/blob/844a9202bf5f40a292dbc54cafe359666678f9f9/futures-util/src/stream/buffered.rs#L128-L133

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rust-lang-nursery/futures-rs/issues/1061#issuecomment-402382876>,
or mute the thread

**Comment by withoutboats** [comment]
> The problem is that `poll` takes time linear in the depth of the call stack. So repeated calls to `.and_then` are O(n^2).

What is `n` here? You suggest in your first post that its the number of times the future is polled, but here you seem to refer to the depth of the stack. Its not quadratic in either factor, so I think you actually mean that it grows linearly in both factors. That's true until the optimizer gets involved (hopefully inlining some of those poll calls), but without benchmarks I don't feel very concerned about this.

**Comment by rpjohnst** [comment]
Combinator-y things like `map` or `and_then` ought to be inlined, which would solve the problem in this case. (We may end up needing to use MIR inlining before the state machine transformation, or some other way of flattening the generated states, but it should be doable.)

For larger cases, if they become an issue, we might also try a [CPS-like approach](https://internals.rust-lang.org/t/pre-rfc-cps-transform-for-generators/7120).

**Comment by cramertj** [comment]
Discussion here seems to have hit a dead end, so I'm going to close this issue. Feel free to comment if you think it should remain open or if there's something that is still unclear.
