### ISSUE TITLE
Crate for pin macros

### ISSUE THREAD

**Issue by MajorBreakfast** [rust-lang-nursery/futures-rs#1127]
I'd like to extract our pin macros into their own crate because they're useful for pinning in general and not tied to futures at all. Here's what I'd like to do:

- Remove the macros from the facade. Implementors can depend directly on the pin macro crate. `#[macro_use]` is going away and an additional line in `Cargo.toml` ins't a burden. So the difference is really just `use pin_utils::pin_mut;` instead of `use futures::pin_mut;`
- Keep the source within the futures repository
- Possible names: `pin-utils` (my favorite), `pin-util`, `pin`, `pin-macros`, `pin-macro` (one day we might want to include not-macro stuff in it as well, though)
- Independent versioning: Start with version 0.1.0

Thoughts?
@aturon 
@cramertj 
and anyone who's reading this 🙂

**Comment by Nemo157** [comment]
CC @withoutboats, @pythonesque and @ashfordneil since this includes unsafe pin accessors and they were discussing them on the Pin API tracking issue. It would be good to have just a single canonical utility library for making pinned types more ergonomic rather than splitting the effort.

@MajorBreakfast I assume this is just https://github.com/rust-lang-nursery/futures-rs/blob/master/futures-util/src/macros/pin.rs, or are there other related macros somewhere else?

`pin-utils` is my favourite as well (but it's going to make me mistype `futures-utils` even more often).

**Comment by MajorBreakfast** [comment]
> or are there other related macros somewhere else?

@Nemo157 It's just the one file

> but it's going to make me mistype futures-utils even more often

I've mistyped this countless times as well ^^'

**Comment by withoutboats** [comment]
I don't think pin helper macros belong in the public API of futures, so this makes sense to me. :)

**Comment by aturon** [comment]
This sounds really great to me!

**Comment by MajorBreakfast** [comment]
https://crates.io/crates/pin-utils

https://github.com/rust-lang-nursery/pin-utils

**Comment by MajorBreakfast** [comment]
With https://github.com/rust-lang-nursery/futures-rs/pull/1185 the futures crate now uses the macros from the `pin-utils` crate.

The change will be formerly announced in the blog post for alpha 3.
