### ISSUE TITLE
Revert Spawn name change back to Executor

### ISSUE THREAD

**Issue by seanmonstar** [rust-lang-nursery/futures-rs#1202]
It seems clearer (to me) that these things are "futures executors", not "spawners". That a particular `Executor` may be simply sending on a channel to the real thing is an implementation detail. I think the difference to me is that `Executor` sounds like a thing that can "execute" futures, whereas `Spawn` sounds like a thing that can *be* spawned.

**Comment by Nemo157** [comment]
As a counter-point I find the separation of concepts much clearer. The `Context` does not need something that is capable of "executing futures", it just needs something that can "spawn a future to run independently". Conversely you can have an "executor" that is incapable of spawning new futures and can only run the one it is given at the top level, even without spawning there's a large overlap in functionality the executor must provide in terms of the "wake system".

As you mention commonly the value passed into the `Context` is not the executor itself, it's some handle that knows how to get a spawned future back to the executor to run. It seems to me that the alternative where the executor type uses internal reference counting or something to both act as the thing executing futures and the thing that can spawn futures onto the executor is the minority case.

I also have plans to experiment with non-owning executors, where the executor is purely concerned with running a set of futures via reference. In that case a `Spawn` type is a handle to a pair of (memory pool, executor) that will allow independently allocating memory for the future and inserting a reference to it into a run list for the executor.

This separation of concepts definitely needs some more documentation work, probably with different information targeted at different user groups. For users of executors they only really need to briefly understand the distinction, an executor is a concrete type that runs all your futures for you, if you need to spawn off separate tasks the context provides a trait for that. For developers of executors we need a more thorough description of what it really means to provide an "executor" since there's no simple trait definition to point to, rather that it consists of a (wake system, run loop, spawn handle) set of requirements.

That last point that an "executor" != `Executor` is probably my biggest issue with the old naming, even though there's a trait with that name just implementing the trait doesn't get you a working futures system. If we had an alternative name for the "top-level executor"/"thing that actually makes it all work" then I'd be fine with the trait to spawn a future being called `Executor`, I just strongly think that these two concepts need a clear division to make talking about the system as a whole easier.

**Comment by MajorBreakfast** [comment]
I agree with @Nemo157. When @cramertj proposed the name change it was a real eye opener to me. I think that the new name fits like a glove. The biggest indicator that the new name is more fitting is (as already mentioned) that the type that implements `Spawn` is often just a sender that sends the future to an executor. And the executor which handles the scheduling and execution is a different type.

**Comment by cramertj** [comment]
@seanmonstar 
> Executor sounds like a thing that can "execute" futures

Yes-- this is why I wanted to rename the trait to `Spawn`. Some things that implement the `Spawn` trait that I have written do not actually play any role in executing futures-- they just spawn them onto something that does know how to run futures. By contrast, `Executor` is something that I'd expect to be able to turn a `Future<Output = T>` into a `T` (like a "block"-er).

**Comment by seanmonstar** [comment]
> Some things that implement the Spawn trait that I have written do not actually play any role in executing futures-- they just spawn them onto something that does know how to run futures.

I've written a bunch of these "lightweight" executors which ultimately send the future to the proper executor, and it never seemed wrong. Those are just implementation details. However, seeing a bounds of `S: Spawn` somewhere is not as clear to me as `E: Executor` was. We also now have `with_spawner` methods on `Context`, which read weirdly, whereas `with_executor` did not.

As an external example, scala's futures consider this thing an `ExecutionContext`.

**Comment by Nemo157** [comment]
`ExecutionContext` also seems like a fine name to me. It’s very close to C#’s `SynchronizationContext` which I have a little familiarity with (confusingly C# also has an `ExecutionContext`, but that’s more like a task-local-storage implementation). Those names both imply “this is not the thing running your tasks, just some sort of context that knows how to communicate with it”.

**Comment by crlf0710** [comment]
I prefer `Spawner` over `Spawn`, since that's its role in the futures system. For verbs traditionally Rust will use `Spawn` to represent `Spawnable`, which is wrong in this case.

**Comment by ehiggs** [comment]
`Spawn` conflates with `posix_spawn` which creates a new process from a given file. As `Spawn` here is about using an existing execution service, it is confusing to existing systems programmers looking through documentation for `the right thing` since one doesn't want to spawn a new process to run a `future`.

If we are leaking an intermediate state between "this is my work" and "this it the thing that can run work" then `stage` sounds like a more appropriate term.

**Comment by cramertj** [comment]
It seems like general consensus is still in favor of `Spawn`, so I don't plan on changing this.
