### ISSUE TITLE
panicked at 'no Task is currently running' for tokio::timer::Delay when using block_on

### ISSUE THREAD

**Issue by redtankd** [rust-lang-nursery/futures-rs#1251]
the code is 

```
use futures::compat::{Future01CompatExt, TokioDefaultSpawner};
use futures::executor::{block_on, ThreadPoolBuilder};
use tokio::timer::Delay;

#[test]
    fn job_on_time() {
        let when = Instant::now() + Duration::from_millis(100);
        assert_eq!(
            1,
            block_on(Delay::new(when).compat().map(|x| {
                assert_eq!((), x.unwrap());
                1
            }))
        );
    }
```

the error message is 
```
---- tests::job_on_time stdout ----
thread 'tests::job_on_time' panicked at 'no Task is currently running', libcore/option.rs:1000:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

the  versions are
```
futures-preview = { version = "0.3.0-alpha.5", features = ["tokio-compat","compat"] }
tokio = "0.1.8"
```

**Comment by Nemo157** [comment]
This is a limitation of the current compat layer, a wrapped 0.1 future still needs an ambient `futures(0.1)::task::Task` available, which 0.3 executors don't setup.

It might be possible to setup the `Task` automatically, but last time I looked at the 0.1 docs for this I didn't see any way to detect whether a task is currently available (except `std::panic::catch_unwind`, but we really don't want that on this path).

Alternatively it's probably easier to have an extra compat wrapper for 0.1 -> 0.3 that sets up the task always, but that will almost certainly panic if either run on a 0.1 executor, or nested in itself.

**Comment by Nemo157** [comment]
(as a side note: even once the `Task` is available Tokio futures will still almost certainly not work on a 0.3 executor since they require an ambient `tokio::reactor::Reactor` as well, it seems like it should be possible to run a standalone reactor next to a 0.3 executor, but I don't know how ergonomic using that would be. It's much easier to just run Tokio futures on Tokio's executor for now).

**Comment by redtankd** [comment]
ok, thank you very much

**Comment by carllerche** [comment]
@redtankd In general, if you want to use any Tokio types, you should use a Tokio runtime.

**Comment by cramertj** [comment]
@Nemo157 
> This is a limitation of the current compat layer, a wrapped 0.1 future still needs an ambient futures(0.1)::task::Task available, which 0.3 executors don't setup.

`task::current` should resolve when using compat because we use [`executor::with_notify`](https://docs.rs/futures/0.1.24/futures/executor/fn.with_notify.html) with our wrapped waker [in the compat impl](https://github.com/rust-lang-nursery/futures-rs/blob/master/futures-util/src/compat/compat01to03.rs#L29). Is there something about this that isn't working correctly?

**Comment by Nemo157** [comment]
@cramertj `executor::with_notify` will panic if run outside a futures 0.1 task, that’s where the above panic is coming from. If you’re using a 0.3 executor the outermost 0.1 compat layer will need to initialise a 0.1 task for this 0.3 task and store it into thread-local storage.

**Comment by cramertj** [comment]
Ah-- you're totally right. IMO we shouldn't be using that function, then-- we should instead use `executor::spawn` and the appropriate `poll_xxx_notify` functions. I'll open a PR for that, unless anyone has objections? Without that, the current tools seem pretty useless.

**Comment by cramertj** [comment]
Opened https://github.com/rust-lang-nursery/futures-rs/pull/1281, which will be needed to make `Spawn` work directly for `AsyncRead`/`AsyncWrite`.

**Comment by cramertj** [comment]
Opened https://github.com/rust-lang-nursery/futures-rs/pull/1282 to use `Spawn` for the 0.1 -> 0.3 compat shim.
