### ISSUE TITLE
Consider have task::park() return Option<Task> instead of panicking when not run on a task

### ISSUE THREAD

**Issue by carllerche** [rust-lang-nursery/futures-rs#131]
When attempting to poll a future while not currently on a task, odds are something will attempt to call `task::park` which will end up in a panic.

I propose to, instead, have the `poll` return `NotReady`. At the root future, the caller will receive `NotReady` and it will be up to the caller to figure out how to handle this. This is more or less how mio (and non-blocking sockets work).

**Comment by alexcrichton** [comment]
I do agree that having `park` panic if the current task isn't set as pretty unfortunate. I'm afraid though that if we return an `Option` here we'd just punt the panic up the stack to everyone calling `task::park`. That is, there's no possible way to recover from `task::park` returning `None` I think because in that case `poll` in an arbitrary future won't be able to fulfill its contract of ensuring a notification is scheduled.

When we chatted about this on IRC, however, the thought was that there'd perhaps be a polling method on `Spawn<F>` which didn't require a `Arc<Unpark>`. You'd call it with the intention of "I'll arrange myself to get notified later" via some other means.

Perhaps that would suffice here?

**Comment by jonhoo** [comment]
Just a minor point, but the use-case you give above fits perfectly for when you're writing test cases for an implementer of `Future` or `Stream`. In that case you may want to quickly check that the future doesn't *currently* resolve. Then your test case is going to do some other stuff, and check again.

**Comment by abonander** [comment]
@alexcrichton 

I might just open a separate issue about this, but I feel like, e.g., `sync::oneshot` doesn't necessarily need to park the task when polled; without a task or a value, it can just return `Async::NotReady`.

I'm trying to use `oneshot` in a futures-aware crate but because I don't want to lock-in users to `futures` if they don't want it, I want to provide a promise-like API where the user can check for completion without operating on a task. I *think* I can do this using `Spawn` internally and provide a no-op `Unpark` impl, but that seems cumbersome.

**Comment by carllerche** [comment]
@abonander The guarantee of returning `Async::NotReady` is that you are notified when the readiness changes. So, unfortunately `Async::NotReady` cannot be returned off task.

**Comment by abonander** [comment]
@carllerche Yes, I realize this is the general guarantee for combinators and stuff, but I'm talking about specifically the `sync::oneshot` abstraction which only requires a task because it uses the `Lock<Option<Task>>` to determine whether or not the sending half was dropped without providing a completion value, which could be implemented with a separate `AtomicBool`.

**Comment by aturon** [comment]
Closing, as this will no longer be relevant in 0.2.
