### ISSUE TITLE
Unable to compile with futures-test as dev-dependency

### ISSUE THREAD

**Issue by Thomasdezeeuw** [rust-lang-nursery/futures-rs#1385]
Adding `futures-test-preview = "0.3.0-alpha.11"` to dev-dependencies causes the following compilation error for me:

```log
error[E0425]: cannot find function `block_on` in module `futures_executor`
  --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-test-preview-0.3.0-alpha.11/src/future/mod.rs:79:44
   |
79 |         thread::spawn(|| futures_executor::block_on(self));
   |                                            ^^^^^^^^ not found in `futures_executor`

error: aborting due to previous error
```

I think this is the case because by default it doesn't enable the `std` features in futures-executor, see https://github.com/rust-lang-nursery/futures-rs/blob/71c59479b538380567907b115ec71799eb03b88d/futures-test/Cargo.toml#L20

Which means `block_on` isn't available, see https://github.com/rust-lang-nursery/futures-rs/blob/71c59479b538380567907b115ec71799eb03b88d/futures-executor/src/lib.rs#L14-L15

I assume the fix is as simple as enabling the `std` feature on future-executor by default, but I don't what other things that would cause.

**Comment by Nemo157** [comment]
The reason this is passing on CI is because it's not included in the `--no-default-features` build, also even if it was https://github.com/rust-lang-nursery/futures-rs/blob/71c59479b538380567907b115ec71799eb03b88d/futures-test/Cargo.toml#L24 would enable the `std` feature even when building via `cargo build --manifest-path futures-test/Cargo.toml --no-default-features` (https://github.com/rust-lang/cargo/issues/4866 is the most relevant issue I think).
