### ISSUE TITLE
mpsc: try_send() erroneously returns error “Full”

### ISSUE THREAD

**Issue by gralpli** [rust-lang-nursery/futures-rs#1386]
Documentation for `mpsc::channel(buffer: usize)` says: “The channel's capacity is equal to `buffer + num-senders`.” If I have two senders and specified that I want to have one additional place in my buffer, both senders should be able to send one element, and thereafter, one of both should be able to send an additional one.

```rust
use futures::channel::mpsc;

fn main() {
    let (mut sender_1, mut receiver) = mpsc::channel(1);
    let mut sender_2 = sender_1.clone();

    // Let both senders occupy their guaranteed slot. This works.
    sender_1.try_send(1).unwrap();
    sender_2.try_send(2).unwrap();

    // There is now one slot left, but if sender_2 tries to send,
    // it encounters an "TrySendError { kind: Full }":
    if let Err(err) = sender_2.try_send(3) {
        println!("sender_2 wasn't able to send: {:?}", err);
    }

    // But sender_1 is able to do so:
    sender_1.try_send(4).unwrap();
}
```
---
I‘m using `futures-preview = "0.3.0-alpha.11` and `rustc 1.33.0-nightly (a2b0f247b 2018-12-30)`.

**Comment by Nemo157** [comment]
This seems correct to me, the first time you send through `sender_1` it occupies the shared slot, then `sender_2` uses up its dedicated slot, you try to send through `sender_2` but the shared slot and its dedicated slot are both in use so it can't send, but then `sender_1` can send because its dedicated slot is still available. The key is that all the capacity is not equal, the senders dedicated slots can't be used by any other senders, as the next sentence says: '_In other words, each sender gets a guaranteed slot in the channel capacity, and on top of that there are `buffer` "first come, first serve" slots available to all senders_'. I think the documentation here could be probably be rewritten a little to make it clearer that the total capacity is not available to all senders.

**Comment by gralpli** [comment]
Oh, okay, I thought each sender uses its dedicated slot first (that‘s how I understood that sentence). Maybe I‘ll make a pull request to improve the documentation here.

**Comment by cramertj** [comment]
Closing, but @gralpli I'd love to see a docs PR if you're interested in writing one! :)
