### ISSUE TITLE
Use a version agnostic await macro

### ISSUE THREAD

**Issue by najamelan** [rust-lang-nursery/futures-rs#1449]
Tokio has a version of await! that takes both 0.1 and 0.3 futures. This is very convenient. It would make sense that macros like `join!` would use this version of await internally, so people can join futures of any version.

In general, it would be most convenient I think if libraries accept both versions of futures transparently as method parameters, and provide 2 methods when the return type is a future, so the client can choose which version they want.

I think that will help the ecosystem migrate.

**Comment by Nemo157** [comment]
0.1 futures are not fully compatible with the `std::future` execution model, they rely on extra global state that is not provided by it.

`tokio-async-await` gets around this by being only partially a `std::future` wrapper, it only allows using `async` intermediary layers as long as the executor and leaf futures are based on 0.1.

`futures(0.3)::compat` includes the extra overhead to make 0.1 futures truly `std::future` compatible, by wrapping them in a compatibility layer that injects the global state they rely on at runtime.

IMO transparently injecting the compatibility layer would not be a good thing long term. It introduces a non-obvious source of overhead, and seems like it would lead to issues with ecosystem fragmentation if library developers decide to stay with 0.1 because they have less pressure to update (while things like the `await!`/`join!` macro may be able to make the `Future` trait compatible across versions (until `await!` becomes a non-macro relatively soon),  APIs will be designed very differently now that they have the ability to use lifetimes like synchronous code).

As soon as `std::future` stabilizes I think libraries should start updating to it, using explicit compatibility layers where needed, then as their dependencies update they can easily remove the compatibility layers.

**Comment by najamelan** [comment]
It doens't look like there's any animo for this, so I'll close it.
