### ISSUE TITLE
AsyncBufReader / AsyncBufWriter

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang-nursery/futures-rs#1519]
Similar to https://github.com/rust-lang-nursery/futures-rs/issues/1512, we've been missing an async equivalent of std's [io::BufReader](https://doc.rust-lang.org/nightly/std/io/struct.BufReader.html) and [io::BufWriter](https://doc.rust-lang.org/nightly/std/io/struct.BufWriter.html). This would be useful to reduce the amount of system calls, and speed up throughput.

**Comment by Nemo157** [comment]
I've experimented with this in embrio with [`trait AsyncBufRead`](https://github.com/Nemo157/embrio-rs/blob/master/embrio-core/src/io/buf_read.rs), an [async `struct BufReader`](https://github.com/Nemo157/embrio-rs/blob/master/embrio-util/src/io/buf_reader.rs) and an implementation of [`async fn read_until`](https://github.com/Nemo157/embrio-rs/blob/master/embrio-util/src/io/read_until.rs) (the latter can definitely be simplified by providing `async fn fill_buf()` on top of `fn poll_fill_buf()` and actually using `async fn` syntax). These have definitely worked well, and it should be straightforward to port `std`-like variants into `futures` (these were a little different than the ones provided in `std` since embrio is `alloc`-less).

**Comment by taiki-e** [comment]
[`std::io::BufWriter` implements `Drop`](https://github.com/rust-lang/rust/blob/3d720d7e617442aaf65df0910e8c9f0fdb0cf31c/src/libstd/io/buffered.rs#L653-L660), and it is convenient. Do you think that async `BufWriter` can also implement it? ([functions that call `flush_buf` (flushes the internal buffer) internally need to receive a context](https://github.com/taiki-e/futures-rs/commit/bcd61df70843e57da1145d91652238c8f339a91f#diff-5c81d940fce4005fbd5fcd27e1c6554eR272). `into_inner` also has the same problem.)

**Comment by Nemo157** [comment]
IMO anyone using an async writer should be calling `close` on it to ensure it's fully flushed and closed, dropping a writer without closing it is allowed to just abandon any outstanding writes (which is something that probably needs documenting on `AsyncWrite`). Having `std::io::Write` implementations set the precedent that dropping will flush outstanding writes and swallow errors is quite unfortunate though.
