### ISSUE TITLE
mpsc channel: Better error types?

### ISSUE THREAD

**Issue by mgeier** [rust-lang-nursery/futures-rs#1579]
I was reading the API docs of the MPSC channel and I was wondering about those types:

```rust
pub struct SendError {
    kind: SendErrorKind,
}

pub struct TrySendError<T> {
    err: SendError,
    val: T,
}

enum SendErrorKind {
    Full,
    Disconnected,
}

pub struct TryRecvError {
    _inner: (),
}
```

What about changing them to `enum`s like this:

```rust
pub enum SendError {
    Full,
    Disconnected,
}

pub enum TrySendError<T> {
    Full(T),
    Disconnected(T),
}

pub enum TryRecvError {
    Empty,
}
```

This would make direkt pattern-matching on the error type possible.

The separate `SendErrorKind` type would not be necessary anymore.

I think this would be backwards-compatible (but I'm not sure about that).

**Comment by seanmonstar** [comment]
These errors are purposefully *not* `enum`s, because adding variants to a public enum is a breaking change.

**Comment by Nemo157** [comment]
Is `#[non_exhaustive]` still not stable yet? Even if not, having a doc hidden extra variant is a pretty widely spread practice.

**Comment by mgeier** [comment]
@seanmonstar I see, thanks! Just out of curiosity, are there plans for adding new variants at some point?

**Comment by cramertj** [comment]
I don't personally anticipate a need to add additional variants, but perhaps someone else in this thread (or maybe @stjepang) can think of reasons for additional errors?

**Comment by seanmonstar** [comment]
IMO, matching structurally on these errors is pretty rare, and so not really worth exposing the variants. 🤷‍♂️

**Comment by cramertj** [comment]
Closing-- feel free to reopen if there's a need for some change here.

**Comment by mgeier** [comment]
@seanmonstar 

> IMO, matching structurally on these errors is pretty rare, and so not really worth exposing the variants.

This may well be the case (I don't know), but independent of that, exposing the variants would have the benefit of creating a more self-documenting API, because all possible errors cases are explicit in public types.

But it may still not be worth changing ...

**Comment by duvallj** [comment]
I'm trying to interface with https://github.com/snapview/tokio-tungstenite, specifically create a stream `.map` from their WebSocketStream and forwards to an `::channel::mpsc::UnboundedSender` As far as I can tell, because the stream produces errors of type `tungstenite::error::Error` and the sink takes `SendError`s, the only way to do this is to achieve some sort of interpolation between the errors.

With the current error structure, i.e. private enum, it is impossible to manually construct a `SendError` to achieve this. As such, could either the enum be made public or some sort of constructor provided? Or am I going about this completely the wrong way?

**Comment by Lonami** [comment]
I support this. Exhaustiveness checking of Rust's `match` is wonderful, and having to resort to checking e.g. `is_disconnected()` when more variants may be added and one would be unaware of them (because the compiler can't catch that) is less than ideal. Also, falling back to `if`-chains instead of `match` makes it more awkward to use.

I don't even approve of the use of `#[non_exhaustive]` here, I think if more variants should be added that ought to be a breaking change.

So the current situation just makes it more painful to do the Right Thing, but these are only my two cents.
