### ISSUE TITLE
Why `join3/4/5`?

### ISSUE THREAD

**Issue by kigawas** [rust-lang-nursery/futures-rs#1742]
https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.17/futures/future/struct.Join5.html

I don't understand why there have to be `joinX` functions.

**Comment by udoprog** [comment]
Because they take a different number of arguments of varying types and Rust doesn't support something called "variadic functions" nor "variadic generics" which would permit a function to take any number of arguments of different types.

So `join` takes two generic arguments, `join3` takes 3 generic arguments, and so forth...

**Comment by kigawas** [comment]
I mean, why not expose the generic and let user define their own joinX? 
The current joinX functions look like they are written when drunk

**Comment by Pauan** [comment]
@kigawas That's what the [`join` macro](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.17/futures/macro.join.html) is for.

**Comment by kigawas** [comment]
@Pauan
I know, then thus the joinX functions doesn't make any sense, if you can define join3/4/5, why not define join6/7/8/9?

**Comment by Pauan** [comment]
> thus the joinX doesn't make any sense

There are advantages and disadvantages to the functions: they don't require `async`/`await`, they have different performance characteristics, and they work with expressions rather than identifiers. That's why both the functions and the macro exist.

> why not define join6/7/8/9?

Because nobody needed it. If you're joining that many Futures, there are plenty of options available:

* You can simply nest it: `join5(join5(foo, bar, qux, corge, lorem), ipsum, dolor, sit, amet)`

* You can use the macro: `join!(foo, bar, qux, corge, lorem, ipsum, dolor, sit, amet)`

* You can use [`join_all`](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.17/futures/future/fn.join_all.html) which works on an Iterator of Futures. But all of the Futures must be the same type.

* If you have a lot of Futures, it's more efficient to use [`FuturesUnordered`](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.17/futures/stream/struct.FuturesUnordered.html) instead of `join_all`.

If you can present a compelling use case for why more `joinX` functions should be added, then they will be added.

**Comment by kigawas** [comment]
For the sake of simplicity and consistency, it'll be a problem that we have "plenty of" options instead of one. 

It's an anti pattern, at least for a Python developer like me. And it's even hard to believe this kind of inconsistency can happen on a so-called "modern system language".

**Comment by Pauan** [comment]
> It's an anti pattern, at least for a Python developer like me.

Rust is not Python. It does not have the same features as Python, it does not have the same goals as Python, it does not have the same philosophy as Python, and it does not have the same design patterns as Python. This is often intentional, it is not a flaw in Rust.

Expecting Rust to be like Python is unreasonable. Even other "modern" languages do not blindly follow Python (see Ruby, C#, F#, Go, Swift, Clojure, etc.)

Rust has static typing. That means it cannot have the typical var-args that Python has. This isn't specific to Rust, it applies to *all* languages with static typing.

That means if you want to be able to join multiple *different* Futures then you need the `joinX` functions (or the `join` macro, which has its own downsides). This is because each Future has a *different type*.

If you want to join multiple of the *same* Future, then `join_all` or `FuturesUnordered` work great. Rust gives you this choice because the choice *matters*: each of these options has different behavior and performance, so you need to choose the right one based on your needs.

Python doesn't need to worry about this because Python has *dynamic typing*, and Python doesn't care about performance. But in Rust you do actually need to care about the type of things, you cannot just mix-and-match different types willy-nilly. You will experience the same thing in *any* language with static typing.

The fact that Rust has static typing does not make it less "modern", or more "inconsistent", it just means that Rust values static type safety, because it has major benefits in catching bugs, dramatically improving performance, and making refactoring much easier.

**Comment by kigawas** [comment]
To sum up, what you want to validate is:
1. If the futures' types are same, then it's easier and a simple `join_all` would just work.
2. If the futures' types are different, then you need `joinX`.

About 2, there are 2 ways. One is about generics (static dispatch) and another is about trait objects (dynamic, with overhead) and rust prefers the previous one, AFAIK.

And in fact, the `joinX` functions is just implemented like:
```rust
generate! {
    /// Future for the [`join`](join()) function.
    (Join, <Fut1, Fut2>),

    /// Future for the [`join3`] function.
    (Join3, <Fut1, Fut2, Fut3>),

    /// Future for the [`join4`] function.
    (Join4, <Fut1, Fut2, Fut3, Fut4>),

    /// Future for the [`join5`] function.
    (Join5, <Fut1, Fut2, Fut3, Fut4, Fut5>),
}
...
```
If you have to implement things like this, then:
1. Why not let the user use `generate!` to define their own `joinX` functions?

2. If you say you can achieve `join10` by combinations of `join5`, then `join5` can also be implemented by combinations of `join` essentially. How the X in `joinX` is taken and what is the rational there is a 5 but not 6? What is the border of why we choose some number but not another number? It is decided by practice? Or some fickle emotion without solid reason?

"Inconsistent" is not about static types or dynamic types, it's about aesthetic like how you design a simplified, neat and understandable API.

**Comment by Pauan** [comment]
> One is about generics (static dispatch) and another is about trait objects (dynamic, with overhead) and rust prefers the previous one, AFAIK.

It's true that Rust prefers static dispatch (for performance, since performance is one of the *primary* reasons to use Rust over other languages).

However, in this case it's not about static dispatch, it really is about static typing:

```rust
let (a, b) = join(ready(1), ready("Hello!")).await;
```

In this case `a` has type `i32`, and `b` has type `&'static str`. This cannot be done with dynamic dispatch (e.g. `Box<Future>`), it requires the `joinX` functions.

> then join5 can also be implemented by combinations of join essentially.

That is true. In fact all of the `joinX` functions can be implemented in terms of just `join`. It would have to do a bit of extra tuple packing/unpacking, but the compiler might be able to optimize that away.

That's rather irrelevant though, since it's just an implementation detail: the API will be the same regardless of *how* it's implemented internally.

> How the X in joinX is taken and what is the rational there is a 5 but not 6? What is the border of why we choose some number but not another number? It is decided by practice? Or some fickle emotion without solid reason?

As I said, nobody needed higher numbers, but if you can provide a compelling use case then they will be added.

API design is always a fuzzy creative area which involves subjectivity, this is true in all languages.

> Why not let the user use generate! to define their own joinX functions?

Generally crates don't expose their internal implementation details unless there's a good reason to do so.

Crates must follow the rules of semver, and so if they expose their internal details then they cannot change those details (except in a major version bump). And those internal details must be documented and maintained. So there is a cost to exposing the details.

And since there's plenty of ways to achieve higher numbers (nesting, macro, `join_all`, etc.) it didn't need to be exposed.

But you're free to file an issue requesting for it to be exported, ideally explaining your use case.

Keep in mind that exposing `generate` isn't enough, you still need to create the `joinX` functions yourself (`generate` doesn't do that, it only creates the wrapper types).

> "Inconsistent" is not about static types or dynamic types, it's about aesthetic like how you design a simplified, neat and understandable API. And I don't think static languages have to compromise.

By all means, please do create a crate which provides the API you prefer. You have all the same building blocks available to you, so there is nothing stopping you from doing so.

And if you do find a better API, you can then send a pull request for it to be added into `futures-rs`, so everybody can benefit. This sort of API improvement happens all the time, and is always appreciated.
