### ISSUE TITLE
[Question] How do you do publish your packages to crates.io

### ISSUE THREAD

**Issue by boskiv** [rust-lang-nursery/futures-rs#1822]
I can't find it in .travis.ci.yml
Is there something special ?
Do you have some helper scripts for that ?

**Comment by Nemo157** [comment]
At the moment the previews are published as a single batch version of every crate, this is likely to change once the alpha releases are over.

You can see an example mass update of the version numbers and metadata in this PR: https://github.com/rust-lang-nursery/futures-rs/pull/1789.

Once that is merged @cramertj publishes them manually (maybe with some scripts?), I assume that step requires stripping dev-dependencies because of cargo's issues with circular dev-dependencies, but shouldn't have any other code changes.

Again, I wouldn't expect this process to stay the same post-alpha, at that point there are some sub-crates that will have only very rare patch releases and no planned breaking releases so they won't need to be published as often as the more unstable utility crates. Once that happens there might be some more structure/documentation to the process.
