### ISSUE TITLE
unnecessary "nightly" feature

### ISSUE THREAD

**Issue by leeopop** [rust-lang-nursery/futures-rs#1856]
Recent change says that "async-await" no longer requires nightly.
However, building alpha.18 version claims that "nightly" feature is not on.
I'm not sure whether removing this feature gate is correct or not, thus simply reporting the compilation error I have.

```{.txt}
error: The `async-await` feature requires the `nightly` feature as an explicit opt-in to unstable features
  --> /home/leeopop/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.18/src/lib.rs:21:1
   |
21 | compile_error!("The `async-await` feature requires the `nightly` feature as an explicit opt-in to unstable features");
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by Nemo157** [comment]
This is referring to the `nightly` cargo feature for the `futures` crate that was used to gate unstable features (since non-`std` crates have nothing really like the `unstable` attribute). That has since been [renamed to `unstable`](https://github.com/rust-lang-nursery/futures-rs/pull/1823) to make it more obvious and is [no longer required when using the `async-await` feature](https://github.com/rust-lang-nursery/futures-rs/pull/1816/files#diff-259a7a0e8388233398357530dd430463L20-L22). Those changes will be in the next alpha release.

**Comment by leeopop** [comment]
Oh, I was working on alpha.18 while looking master's README.
I'm looking forward to see the next release!
