### ISSUE TITLE
take_while variant that eventually returns the original stream?

### ISSUE THREAD

**Issue by sunshowers** [rust-lang-nursery/futures-rs#400]
Does it make sense to add a way or alternative to `TakeWhile` that consumes `self` and returns the original stream once the predicate returns false?

My use case is fairly complicated, but here goes:

I'm in a situation where I have two separate codecs (for layering reasons), and I want to have a single stream which could return values from either codec by performing a "codec upgrade" dynamically. (Let's assume for now that I'm only interested in the `decode` side of the codec.)

Concretely, I have a *base* codec and one or more *upgrade* codecs. The *base* codec returns an enum of `Header`, `PayloadStart`, `Payload` and `PayloadEnd`. `Payload` contains a `Vec<u8>`.

Let's call the result of applying the base codec on an Io object the *base stream*, and the result of applying an upgrade codec onto a payload 

* `Header` should be passed through unconditionally.
* `PayloadStart` should cause future values to be passed via the appropriate upgrade codec until the next `PayloadEnd`.
* `Payload`s should cause the inner `Vec<u8>` to be extracted and run through the upgrade codec, and whatever comes out of there should be returned.
* `PayloadEnd`s should cause a downgrade back to values from the base codec.

The best way to do that seems to be to have a wrapper stream with the notion of a "current stream".

From the base stream:

* `Header`s get passed through.
* `PayloadStart` should cause a new stream to be created which consumes the base stream and layers the upgrade codec on top of future `Payload` objects.
* `PayloadEnd` should cause the upgrade codec to no longer be applied and for us to switch back to the original stream.

Seems like I can do the first two using `take_while`, but not the third one.

**Comment by sid0** [comment]
Thinking about it a bit more, we may want to have a general notion of "stream that wraps a stream and transforms it temporarily", returning the original stream at the end. The `TakeWhile` variant could use this, and so could my upgrade stuff.

**Comment by alexcrichton** [comment]
Note that in general we've considered adding get_ref/get_mut/into_inner to almost all the combinators to handle use cases like this, would that solve your use case here?

**Comment by sid0** [comment]
Yeah, it would! :)

I've implemented my own combinators with those methods for now.

**Comment by sid0** [comment]
One thing I wanted to flag is that since I was using dynamic dispatch across streams produced by a variety of codecs (all with the same `In`), this ended up being quite complicated. I defined a couple of traits:

```rust
/// A stream that wraps another stream. into_inner consumes this stream and
/// returns the original stream.
pub trait StreamWrapper<S: Stream> {
    fn into_inner(self) -> S;
}

/// A stream that wraps another stream. into_inner consumes this stream and
/// returns the original stream.
///
/// This is a boxed version of StreamWrapper, meant to be used for trait
/// objects.
pub trait BoxStreamWrapper<S: Stream> {
    fn into_inner(self: Box<Self>) -> S;
}
```

Then I defined a trait for trait objects that implemented both `Stream` and `BoxStreamWrapper`:

```
type MappedStream<T> = Map<TakeWhile<PartStream<T>, fn(&Part) -> BoolFuture, BoolFuture>, fn(Part) -> Vec<u8>>;

pub trait InnerStream<T>: Stream<Item=InnerPart, Error=io::Error> + BoxStreamWrapper<MappedStream<T>> where T: Read + 'static {
}

impl<T, U> InnerStream<T> for U where U: Stream<Item=InnerPart, Error=io::Error> + BoxStreamWrapper<MappedStream<T>>, T: Read + 'static {
}

pub type BoxInnerStream<T> = Box<InnerStream<T, Item=InnerPart, Error=io::Error>>;
```

At that point I could use `Box<InnerStream<T>>` effectively.

There might be a simpler way to do this -- not sure.

**Comment by alexcrichton** [comment]
Ah yeah dynamic dispatch would throw a number of wrenches into this most likely, unfortunately

**Comment by robey** [comment]
I had the same problem, for the same reason (parsing an inner stream), and became convinced that you need to box the original stream to make it work, because you need to return two new objects, each of which will hold a reference to the original. You can avoid most contention by having the inner stream "switch" modes exactly once.

I coded this up with tests, but ended up not using it because I could handle it better with an enhanced version of StreamGenerator:

https://github.com/robey/lib4bottle-rs/blob/master/src/stream_split.rs

**Comment by alexcrichton** [comment]
Thanks for the update @robey!

I also just pushed up a commit to this crate which adds a bunch of `get_ref` and such methods to combinators.
