### ISSUE TITLE
Consider deprecating Future::select

### ISSUE THREAD

**Issue by carllerche** [rust-lang-nursery/futures-rs#625]
`select2` is the more flexible option and I have seen some questions of the "Why can't I do X with `Future::select`", so it seems having it around is leading to some confusion.

I am happy to submit a PR, but since it would take a bit of work to move the current usage of `select` -> `select2`, I thought I would open an issue first to see if this would be an acceptable change.

**Comment by alexcrichton** [comment]
I personally regret the `concat` -> `concat2` transition in terms of "the method you want for sure has this weird `2` at the end", so if we really want to do this again I'd personally prefer to find a better name for `select2` before we deprecate `select`. It may be too late though with `select2` already "stable" though...

**Comment by carllerche** [comment]
IMO `concat` and `select` are the right names, which means 0.2 should have the fns named that. Maybe there is a strategy to bump to 0.2 w/ minimal breakage.

**Comment by alexcrichton** [comment]
Right yeah I agree that the original names are the way to go, but we have no timeline for 0.2 and it's likely pretty far out, which means we're now approaching a crate where every function is called "foo2". This may mostly just be a concern for new functions in the future though as `select2` is already there, and we probably should have just found a better name before adding that.

**Comment by carllerche** [comment]
The main issue I am seeing is people find `select` and then hit the limitations (that select2 provides) but get stuck there. I've seen this a few times in #rust & the tokio gitter.

**Comment by alexcrichton** [comment]
To be clear I think we should just go ahead and do this, I'm mostly just pointing out that this will have a cost we're going to pay for along time which is that the "nice" API has this weird "2" at the end of it.

**Comment by KasMA1990** [comment]
While on the subject of the `select` name, I feel it's really opaque. I only just learned today that the name comes from Unix, so there's a bunch of history attached to it, but as someone who isn't familiar with the name, it's a bit hard to make sense of. Would it make sense to call it `select_first` instead in some hypothetical version 0.2? That would make it much clearer to me at least what is happening. I know it's kind of weird with `select_ok` also being present without any overloading, since they're basically doing the same thing, but it would still be an improvement I think.

**Comment by alexcrichton** [comment]
Seems plausible!

**Comment by alexcrichton** [comment]
Replacement happened in https://github.com/rust-lang-nursery/futures-rs/pull/755, @KasMA1990 want to open up a separate issue for the rename?

**Comment by KasMA1990** [comment]
Sure, I opened #760 :)
