### ISSUE TITLE
API structure for thread-level executor

### ISSUE THREAD

**Issue by aturon** [rust-lang-nursery/futures-rs#650]
There are a couple of discrepancies in the branch from the RFC:

- The `thread` module was renamed to `current_thread`
- The `TaskExecutor` was renamed to `CurrentThread` (despite there also being a `DaemonExecutor`), and the APIs were moved under it, rather than remaining free functions.

Would be good to get the rationale for these changes written out, since these points were discussed at some length on the RFC thread.

**Comment by aturon** [comment]
cc @carllerche

**Comment by carllerche** [comment]
The RFC did not come to a conclusion re: naming, so I would not have called the issue settled. The PR represents an attempt to address these issues.

There were some valid issues raised with naming it `thread`. The one that most resonated with me was that, if I saw `thread::foo` in rust code, I would naturally think it was the `std::thread` module. Another one is that the module really isn't a "thread executor" (that sounds more like a thread pool). "current thread" is better naming IMO. 
For other issues, see the RFC comment thread.

Another change since the RFC is that this executor isn't used for waiting on a future at the edge anymore. It's really just the current thread executor.

I explained why I moved the fns to a type instead of keeping them free in the PR.

The reason why I used `CurrentThread` instead of `TaskExecutor` was to reduce the number of types that are introduced. IMO the `CurrentThread` executor is the primary type and should be made as such.

`DaemonExecutor` remains as a decoration around `CurrentThread` that spawns tasks with the daemon flag set.

**Comment by aturon** [comment]
> I explained why I moved the fns to a type instead of keeping them free in the PR.

Here's what the PR says:

> The PR just proposes a bucket of free functions. Instead, I put all of these functions on `executor::CurrentThread`.

This doesn't really give any rationale. I don't personally have a super strong preference either way, but the RFC design was striving for usage ergonomics (without having to do `CurrentThread::current()` each time).

> The reason why I used `CurrentThread` instead of `TaskExecutor` was to reduce the number of types that are introduced. IMO the `CurrentThread` executor is the primary type and should be made as such.

Makes sense, but I believe this is a direct consequence of the above. That is, in the design proposed in the RFC, there are also just two types (the executor types), which are ways of wrapping up the free functions in the module.

**Comment by aturon** [comment]
Oops, turned out I was missing a key detail: the functions are not methods, so you don't need to create an instance. Thus, the ergonomics are equivalent.

I think I'm :+1: for how things currently stand.

**Comment by carllerche** [comment]
@alexcrichton https://github.com/alexcrichton/futures-rs/blob/tokio-reform/src/executor/current_thread.rs#L14-L27

The fns do not take self.

**Comment by aturon** [comment]
@alexcrichton Yeah I made the same mistake when re-checking the code; they're static functions.

My point about ergonomics is based on the likely import: `use futures::executor::CurrentThread;` which then allows you to write `CurrentThread::block_with_init`.

**Comment by carllerche** [comment]
@aturon is this sitll an issue?

**Comment by carllerche** [comment]
I assume this issue is resolved by #699 and should be closed now?

**Comment by aturon** [comment]
Yep, thanks!
