### ISSUE TITLE
How can I implement `Future` if all I can do from `poll` is *actually* `poll`? (Also docs are out of date and/or misleading)

### ISSUE THREAD

**Issue by sgrif** [rust-lang-nursery/futures-rs#702]
So I'm taking another look at async IO for Diesel. I've basically operated under the assumption that I need to use tokio and operate at the TCP level if I want to do this. However, libpq, which our sync implementation is based on, provides async capabilities. I figured I'd explore if it was even remotely feasible to do this. I suspect the answer is no, but I wanted to confirm that and/or bring to attention of the team that this appears to be impossible.

For some context, here's the intended flow from the PG docs:

> A typical application using these functions will have a main loop that uses select() or poll() to wait for all the conditions that it must respond to. One of the conditions will be input available from the server, which in terms of select() means readable data on the file descriptor identified by PQsocket. When the main loop detects input ready, it should call PQconsumeInput to read the input. It can then call PQisBusy, followed by PQgetResult if PQisBusy returns false (0).

Oh cool, it just wants me to call `poll(2)`! Presumably that means I can just `impl Future`, have `Future::poll` call `poll`, map that to `Async::NotReady` when needed, and it'll work! Well no, that just leads to a future which is polled exactly once and never resolves...

Note: At this point, someone is probably just saying "oh well clearly tokio is just missing an API that takes a raw file descriptor and adds that to it's event loop". That is true, but also completely misses the point I'm trying to make here.

Note 2: I am probably saying `poll(2)` when I should be saying `select(2)`. That is rather irrelevant.

So let's look at the docs for `Future::poll`. First of all, I find the fact that the docs for this method say "learn more at tokio.rs" incredibly troubling. My understanding was that the intention was for futures != tokio, but that really seems to be untrue in practice. The only alternative appears to be `futures-cpupool`, which has no usage example in its README. There are a few (very small) examples in the module docs, which use `Future::wait`, a method that the documentation states should not be used.

Anyway ignoring that link, we are told that `poll` is expected to call `task::park`, and then somehow call `unpark` when it's ready to be polled again. There's a couple of problems here. First of all, there is no `task::park`. Let's look at the `task` module docs I guess. Oh cool, another "to learn about this module, visit tokio.rs". Are we still trying to claim that futures != tokio? As best I can tell, it is referring to `task::current`? The second problem is that `Task` appears to have no `unpark` method as the documentation says. There's a deprecated `Unpark` trait, but it has no implementors... It says to use the `Notify` trait, which also has no implementors... I'm going to assume that this means I should be using `Task::notify`.

(protip: If these were actually linking to the relevant methods, cases where a method has been deprecated/removed but not updated in the docs are easily found by a dead link checker)

Ignoring the details of *how* we go about doing this though, this leaves the original problem (I have a future which will return `Async::Ready` or `Async::NotReady` based on the result of `poll(2)`) in an odd place. So `Future::poll` not only has to poll, but also has to have some side effect of registering "something" to be told when the future will progress... My understanding was that Rust futures used a pull model. This is not a pull model. This is very specifically a push model.

So it seems my only option is to implement my own event loop, have whatever data structures I'm using take some sort of reference to that event loop, and then require users to call some method on that event loop which eventually calls `poll(2)`. This would make me completely incompatible with the rest of the ecosystem, and seems untenable.

However, this also gets at what appears to be a critical piece of missing information in the type system... A future created which is intended to use tokio is not going to ever work unless you are working with a tokio event loop. Shouldn't this be represented in the type system? If I did have my own future with its own event loop, surely we want to prevent someone passing that to `tokio_core::reactor::Core::run`, since that will result in their program running in an infinite loop.

More importantly, this should be reflected in the type system for crates that are attempting to build on other futures. Let's say for example that I have a crate that takes some future, logs its result to a file, and then yields it. Presumably I'm writing to that file using async IO through tokio. The problem is that if the future I'm given is from anything *other* than tokio, it just straight up doesn't work. This seems like something we should be preventing at compile time.

Finally, `poll` seems like a really bad name. Generally the concept of "polling" something implies that it doesn't have other side effects. You ask if it's ready or not. I would expect that I could implement `Future::poll` purely in terms of `poll(2)`. I think that it's a major design flaw if that is not the case, but at bare minimum that method should be renamed to make its role more clear.

**Comment by alexcrichton** [comment]
Setting aside naming/documentation/deprecation/etc issues (sorry about those!) binding to a library that requires `poll` and such is actually pretty hard to do, but still possible! We're actively working on the naming/documentation issues and such as well, we're always seeking feedback!

You might find the [unix implementation of `tokio-curl`](https://github.com/tokio-rs/tokio-curl/blob/master/src/unix.rs) of interest. Namely curl-the-library has a similar async interface where it wants you to inform it about activity on file descriptors (itself in an epoll-like interface rather than poll-like). In general you shouldn't need your own event loop but instead you'll use a `PollEvented` structure in Tokio with a custom file descriptor, and that's how you'll register task notifications and such (`poll_ready` and such on that type).

To answer some of your specific questions though ...

> Oh cool, it just wants me to call poll(2)! 

Most of the time! In general it should be ok to rely on what Tokio is doing (epoll under the hood) and just translate-on-the-fly. I don't think it'll be required to literally call the `poll` syscall per se.

> First of all, I find the fact that the docs for this method say "learn more at tokio.rs" incredibly troubling. 

We're working on this! @aturon has been working on a "futures book" which should have a much better learning curve for the various concepts and also help draw the line between futures and Tokio. Right now we just happen to have a lot more documentation at tokio.rs.

> Anyway ignoring that link, we are told that poll is expected to call task::park, and then somehow call unpark when it's ready to be polled again. 

Indeed this is a crucial part of the `Future::poll` function to understand! You're right in that they're now call `task::current` and `Task::notify`.

> However, this also gets at what appears to be a critical piece of missing information in the type system... 

This actually is sort of encoded into the typesystem right now surprisingly! To work with Tokio types you typically need an instance of `Handle` or `Remote` which represents a reactor. With the upcoming `tokio` crate, however, this will no longer be necessary and there won't be a type-level distinction per-se, but you'll get errors at runtime if things aren't configured quite right. (early on, hopefully easy to debug errors)

> The problem is that if the future I'm given is from anything other than tokio, it just straight up doesn't work. 

Actually it should work! Most of the underlying aspects of futures and such are agnostic to what's implementing them so long as they adhere to the `Future::poll` interface. It ends up being a little subtle how it all works together but rest assured we've tested cross-event-loop implementations (Tokio + glib in the same process for example) and it works out alright.

> I think that it's a major design flaw if that is not the case, but at bare minimum that method should be renamed to make its role more clear.

Thanks for the info! We'll be sure to take this into consideration for possible releases of `futures`.

**Comment by dwrensha** [comment]
> My understanding was that the intention was for futures != tokio, but that really seems to be untrue in practice.

> A future created which is intended to use tokio is not going to ever work unless you are working with a tokio event loop.

Here's how I like to think about it.

Yes, at the foundation, we always need to have something to act as a source of events and a driver of execution. `tokio-core` and `futures-cpupool` are the primary crates that currently fulfill this role, and there could conceiveably be a variety of others as the ecosystem evolves. When you dig deep enough through the layers of implementation, futures always bottom out in such a foundational implementation.

However, when you write futures for a higher-level library, usually your implementation will not have access to that low-level foundation, as it will be hidden behind generic type parameters. Instead, you will compose your future out of simpler futures, whose concrete types will be determined elsewhere. When you are composing these futures, you don't need to worry about whether it's tokio or whatever under the hood -- you just think about them as futures.

Suppose your goal were to have async Diesel that does not depend on `tokio`. I imagine you could achieve that by splitting things up as follows. You write `postgres-futures`, which defines an async interface to postgres solely in terms of futures/streams/sinks. Then you write a concrete implementation of that interface in terms of tokio, and call it `postgres-tokio`. Then when someone uses aysnc Diesel, they can plug in `posgres-tokio` to Diesel to get it to work, or they could provide their own alternative implementation of `postgres-futures`, say `windows-postgres-futures`, and plug that in instead. The core Diesel logic does not need to care about the underlying implementation.

**Comment by skade** [comment]
I'd like to note that there _are_ other futures implementations, like the one from GTK, backed by glib reactors. It's also supported by future-rs developers.

https://github.com/antoyo/futures-glib-rs

**Comment by aturon** [comment]
I'm going to close this out given the complete revamp with 0.2, and the forthcoming additional documentation (book).
