### ISSUE TITLE
Consifer adding `wait` or `drain` or similiar method for `Stream`

### ISSUE THREAD

**Issue by andreytkachenko** [rust-lang-nursery/futures-rs#707]
I constantly facing with problem that I need convert stream into future, but only when stream will be drained. Here is the signatue
```rust
fn drain(self) -> impl Future<Item = (), Error = Stream::Error>;
```

**Comment by alexcrichton** [comment]
Does something like `.for_each(|_| Ok(()))` work?

**Comment by friedrich** [comment]
For me the function would be useful if it required that `Self::Error == ()`, so one can be sure that the stream runs to completion and is not interrupted on error.

**Comment by najamelan** [comment]
`.for_each( |_| ready(()) )` does work. However it doesn't convey meaning very well for someone reading the code. I also don't know how it's for performance, but it does seem a workaround at best.

I really find `into_future` to be what I expected to do this. I wonder what `into_future` currently adds over `next`. Does anyone use it. That being said, maybe `drain` is a good name. I'm not sure what the best way of implementing it would be. I suspect the foreach construct isn't the best way of doing it.

**Comment by cramertj** [comment]
I think this is easy enough to write in-place now that async/await is stable.

**Comment by folex** [comment]
I'm not sure how to utilize async/await here, but I use
```rust
stream.forward(futures::sink::drain())
```
It's not very concise, but I think it conveys intention pretty well. Hope that will be of help for those who come here through google like I did quite a few times.

**Comment by ModProg** [comment]
> ```rust
> stream.forward(futures::sink::drain())
> ```
While this woks it also requires to have a `.map(Ok)` in front of in some cases, due to `Drain` wanting an Error of `Infallible`. 
Would be really nice to have an actual drain method.

In my use case I have different errors, that can cause a web endpoint to fail. Before returning, I need to drain the stream, so I have the `.map(Ok).forward(futures::sink::drain())` a lot there. Could use `.for_each(|_| ready(()))` as well, but a dedicated `drain()` method on the `StreamExt` trait would be really helpful.
