### ISSUE TITLE
Consider releasing the tokio-reform branch

### ISSUE THREAD

**Issue by carllerche** [rust-lang-nursery/futures-rs#724]
Is there a plan to cut a release of futures 0.1.x w/ the tokio-reform branch merged?

**Comment by aturon** [comment]
Not at-is, since a bunch of that would be immediately shifted around in 0.2. 

We're [full steam on the 0.2 release](https://github.com/rust-lang-nursery/futures-rfcs/pull/1#issuecomment-363247106), which could be out the door as soon as this week. The only real sticking point now is the [`Context` argument question](https://github.com/rust-lang-nursery/futures-rfcs/pull/2), which continues to garner a passionate but mixed response. But I don't think there's likely much *new* to be said there; it just needs a decision.

**Comment by carllerche** [comment]
Well, as I mentioned to @cramertj over IRC, I plan on releasing tokio 0.1 this week kind of as a "preview".

It will depend on tokio-io 0.1, mio 0.6, futures 0.1, etc... and will allow a chance for greater validation of the changes.

Then, in may be 4~6 weeks, I would expect a release w/ a full stack breaking change.

I've been assuming until now that `current_thread` would be available in 0.1, but I can create a temporary crate for it I guess.

**Comment by aturon** [comment]
@carllerche OK, that sounds great!

It should be super easy to define a `current_thread` crate on top of `FuturesUnordered` during this validation period, so that sounds like a good plan.

**Comment by aturon** [comment]
I'm gonna go ahead and close this out. Let's keep in touch to coordinate the futures 0.2 and tokio 0.2 releases well.
