### ISSUE TITLE
HashMap-like Entry API for Task-Locals

### ISSUE THREAD

**Issue by cramertj** [rust-lang-nursery/futures-rs#753]
@carllerche made a good point that with the new `task::Context` API, we no longer need the `with` API for safety, and could instead provide more ergonomic task-local accessors that resemble the existing APIs on `HashMap`.

**Comment by bill-myers** [comment]
Are task-local variables really needed?

Aren't they a bad idea just like putting the context itself in TLS was?

Also, after removing them "task context" can be renamed to a better name, which is something like "WakerProvider" or "Notification" or "Waker" (renaming the current waker to WakerHandle) or similar, since all it does is provide a way to notify and has nothing to do with anything that would be called a "task".

**Comment by carllerche** [comment]
@bill-myers See the [executor RFC](https://github.com/rust-lang-nursery/futures-rfcs) which is being designed using the assumption that task locals are a thing.

**Comment by bill-myers** [comment]
Why not have the "task context" parameter be a pair of an executor reference and a waker mechanism them?

This seems just like a repeat of the task context TLS mistake.

**Comment by carllerche** [comment]
> This seems just like a repeat of the task context TLS mistake.

Not sure why you call it a mistake. There are valid use cases for it. I was just pointing out the executor as a valid use case.

**Comment by bill-myers** [comment]
The RFC to change it to not use TLS has been approved, so it seems to have been a mistake by definition.

I think it's the same because task local variables, just TLS, introduce "variables" that may or may not be set and it's not possible to tell at a glance if it's set or not upon entry to a function or that it even exists.

An explicit executor field or accessors in an opaque field instead are far more explicit and discoverable, and make sure that an executor is always set (of course this is not true for any future opaque accessors that will have to have a default, or code that constructs the task context will break).

**Comment by carllerche** [comment]
Why does it matter if variables have been set or not if they do not alter the observable behavior from the POV of the caller?

**Comment by bill-myers** [comment]
Because if a variable is required to be set by the function, then a panic has to happen instead of the compiler error that would happen if normal function parameters were used and the parameter was missing?

BTW, the executor RFC does seem to propose something similar to the opaque accessors with the "with_spawn" and "with_notify" accessors (although for some reason they seem to take a closure instead of just return a modified task context), so I'm a bit confused on why there is talk of an HashMap-like API here.

Or maybe I'm misunderstading and this is not about providing arbitrary task-local variables?

**Comment by carllerche** [comment]
@bill-myers 

> Because if a task-local or TLS variable is required to be set by the function, then a panic has to happen

That *would* alter the observable behavior from the POV of the caller. I'm asking why task-local variables are mistake if they are used in a way that does not alter the observable behavior from the POV of the caller.

**Comment by seanmonstar** [comment]
The approval to change task context to argument from TLS does not imply TLS is a mistake. I'd offer that calling it as such is a little combative, and suggests that anyone using TLS is making a mistake, when really, all decisions are usually based after comparing pros and cons.

**Comment by aturon** [comment]
Closing -- this is done.
