### ISSUE TITLE
Tracking for `Enter` API

### ISSUE THREAD

**Issue by aturon** [rust-lang-nursery/futures-rs#771]
The executor revamp slimmed down the `Enter` API under the assumption that executor-local storage would obviate the need for the bigger API we had before.

This issue will track that change, and whether `Tokio` 0.2 is able to work with the slimmed down API or needs more functionality (and why).

**Comment by aturon** [comment]
@carllerche, any news here?

**Comment by carllerche** [comment]
I have currently only used the current API of `Enter`. However, to do so required adding the following API to my threadpool: https://github.com/tokio-rs/tokio/blob/master/src/runtime.rs#L238-L242

AFAIK, other potential executors like rayon do not have such an API, so in order to integrate they would need to do something similar.

**Comment by aturon** [comment]
Thanks @carllerche, closing.

**Comment by carllerche** [comment]
Ok, just to be clear, it will not be possible to integrate the Tokio Reactor with the Rayon executor (for example) unless rayon adopts a similar api as the tokio pool.

**Comment by aturon** [comment]
Understood. I think the "around worker" API is a good one.
