### ISSUE TITLE
Update `futures-macro-async` proc-macro2 usage from 0.2 to 0.3

### ISSUE THREAD

**Issue by peterdelevoryas** [rust-lang-nursery/futures-rs#956]
Currently, I can't seem to get `#[async]` to be found with `features = ["nightly"]`, and `cd futures-macro-async; cargo build --features nightly` shows that the crate is currently broken from the new `proc-macro` api. I actually made a [PR](https://github.com/alexcrichton/futures-await/pull/88) to `futures-await` doing this update, not realizing that I probably should have been making the changes to this repo, because `futures-await` is deprecated now. (I think? Maybe not though?) Anyways, I'm still not really sure why I'm getting the "not found" error, which is another issue that probably needs to be created.

Edit: Oh I [see](https://github.com/rust-lang-nursery/futures-rs/commit/ed95dec87fb05cefc8fff0b6a25819304d463739) now why it's not being found!

**Comment by peterdelevoryas** [comment]
Oh woops, maybe I'm out of the loop, because it looks like #940 has all the same changes as my `futures-await` PR? This issue can be closed if this is all known/being reviewed/etc!

**Comment by hcpl** [comment]
AFAIK https://github.com/alexcrichton/futures-await is for tracking `futures-await` 0.1 (evidence from https://github.com/alexcrichton/futures-await/pull/84#issuecomment-379222881); and this repo contains everything for 0.2 release. I'm sure from now on most would want to contribute to this one, though seeing this PR: https://github.com/alexcrichton/futures-await/pull/86 makes me think that `futures-await` 0.1 branch will still be supported for some time.

And just to clear more confusion around repo/crate names, instead of a `future-await` crate that depends on `futures-await-async-macro` and `futures-await-await-macro`, the async/await functionality is now covered by `futures-async-runtime`, `futures-macro-async` and `futures-macro-await` (which haven't been published yet, as you found out from [this commit](https://github.com/rust-lang-nursery/futures-rs/commit/ed95dec87fb05cefc8fff0b6a25819304d463739)).

**Comment by peterdelevoryas** [comment]
Fixed by #940, closing!
