### ISSUE TITLE
#[async] panics with latest nightly (66363b288 2018-04-28)

### ISSUE THREAD

**Issue by sdroege** [rust-lang-nursery/futures-rs#992]
Code in question is https://github.com/gtk-rs/examples/blob/pending/src/bin/gio_futures_await.rs

You can build/run it with `cargo +nightly run --features futures-nightly --bin gio_futures_await`, and it fails as follows

```
error: custom attribute panicked
  --> src/bin/gio_futures_await.rs:23:1
   |
23 | #[async]
   | ^^^^^^^^
   |
   = help: message: unsupported character _

error: aborting due to previous error
```

With the previous nightly the same code compiled just fine. How can more debug information, like a backtrace, for the procedural macro? Just setting `RUST_BACKTRACE=1` does not seem to be sufficient.

This is with futures 0.2 from crates.io

**Comment by sdroege** [comment]
The same happens with latest GIT of futures and all related crates

**Comment by ngg** [comment]
It seems to be unrelated to another current nightly breakage #994 :disappointed:
A workaround is possible to modify https://github.com/gtk-rs/examples/blob/pending/src/bin/gio_futures_await.rs#L55 to have `let _x = ...` instead of `let _ = ...`, but I don't understand why it doesn't work. `cargo-expand` shows a seemingly valid macro expansion. You also need to enable the `proc_macro_non_items` feature in that file but at least for that there is a straight-forward compiler error after you change `_` to `_x`.

**Comment by sdroege** [comment]
Thanks it indeed does now. `proc_macro_non_items` was not required before latest nightly though, but it is now.
